<a href="https://colab.research.google.com/github/hamda1234567/Tabaarak_ICT-practical/blob/main/machine-learning/student_at_risk.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DAY ONE - AI FOUNDATIONS AND SETUP

## loading and reviewing data

In [3]:
import pandas as pd

In [4]:
df= pd.read_csv("student-por.csv",sep=";")

In [5]:
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13

In [6]:
df.tail()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
644,MS,F,19,R,GT3,T,2,3,services,other,...,5,4,2,1,2,5,4,10,11,10
645,MS,F,18,U,LE3,T,3,1,teacher,services,...,4,3,4,1,1,1,4,15,15,16
646,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,1,1,5,6,11,12,9
647,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,6,10,10,10
648,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,4,10,11,11

In [7]:
df.shape

(649, 33)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 649 entries, 0 to 648
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      649 non-null    object
 1   sex         649 non-null    object
 2   age         649 non-null    int64
 3   address     649 non-null    object
 4   famsize     649 non-null    object
 5   Pstatus     649 non-null    object
 6   Medu        649 non-null    int64
 7   Fedu        649 non-null    int64
 8   Mjob        649 non-null    object
 9   Fjob        649 non-null    object
 10  reason      649 non-null    object
 11  guardian    649 non-null    object
 12  traveltime  649 non-null    int64
 13  studytime   649 non-null    int64
 14  failures    649 non-null    int64
 15  schoolsup   649 non-null    object
 16  famsup      649 non-null    object
 17  paid        649 non-null    object
 18  activities  649 non-null    object
 19  nursery     649 non-null    object
 20  higher      649 non-null    object
 21  internet    649 non-null    object
 22  romantic    649 non-null    object
 23  famrel      649 non-null    int64
 24  freetime    649 non-null    int64
 25  goout       649 non-null    int64
 26  Dalc        649 non-null    int64
 27  Walc        649 non-null    int64
 28  health      649 non-null    int64
 29  absences    649 non-null    int64
 30  G1          649 non-null    int64
 31  G2          649 non-null    int64
 32  G3          649 non-null    int64
dtypes: int64(16), object(17)
memory usage: 167.4+ KB

# Day 2 EDA

In [9]:
new_df = df.copy()

In [10]:
new_df.isnull().sum()

# isn()
new_df.isna().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

In [11]:
# drop()
new_df.drop(columns=["school"])
new_df


# drop index
new_df.drop(index=0)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13
5,GP,M,16,U,LE3,T,4,3,services,other,...,5,4,2,1,2,5,6,12,12,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644,MS,F,19,R,GT3,T,2,3,services,other,...,5,4,2,1,2,5,4,10,11,10
645,MS,F,18,U,LE3,T,3,1,teacher,services,...,4,3,4,1,1,1,4,15,15,16
646,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,1,1,5,6,11,12,9
647,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,6,10,10,10
648,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,4,10,11,11

In [12]:
# dropna()
new_df.dropna()

# subset
new_df.dropna(subset=["school"])

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644,MS,F,19,R,GT3,T,2,3,services,other,...,5,4,2,1,2,5,4,10,11,10
645,MS,F,18,U,LE3,T,3,1,teacher,services,...,4,3,4,1,1,1,4,15,15,16
646,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,1,1,5,6,11,12,9
647,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,6,10,10,10
648,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,4,10,11,11

In [13]:
# filnna()
new_df["school"].mode()

0    GP
Name: school, dtype: object

In [14]:
new_df["school"]=new_df["school"].fillna(new_df["school"].mode()[0])

In [15]:
# numerical
new_df["age"].median()

17.0

In [16]:
new_df["age"].fillna(new_df["age"].median()).astype(int)

0      18
1      17
2      15
3      15
4      16
       ..
644    19
645    18
646    18
647    17
648    18
Name: age, Length: 649, dtype: int64

In [17]:
# dupliactes
# False, first,last
new_df[new_df.duplicated(keep="last")]

Empty DataFrame
Columns: [school, sex, age, address, famsize, Pstatus, Medu, Fedu, Mjob, Fjob, reason, guardian, traveltime, studytime, failures, schoolsup, famsup, paid, activities, nursery, higher, internet, romantic, famrel, freetime, goout, Dalc, Walc, health, absences, G1, G2, G3]
Index: []

[0 rows x 33 columns]

In [18]:
new_df=new_df.drop_duplicates()

In [19]:
new_df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13

In [20]:
new_df["at_risk"]=(new_df["G3"]<10).astype(int)

In [21]:
new_df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,at_risk
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,3,4,1,1,3,4,0,11,11,0
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,3,3,1,1,3,2,9,11,11,0
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,3,2,2,3,3,6,12,13,12,0
3,GP,F,15,U,GT3,T,4,2,health,services,...,2,2,1,1,5,0,14,14,14,0
4,GP,F,16,U,GT3,T,3,3,other,other,...,3,2,1,2,5,0,11,13,13,0

In [22]:
features = [
    "studytime", "failures", "schoolsup", "famsup", "activities",
    "higher", "internet", "famrel", "health", "absences"
]

X=new_df[features].copy()

In [23]:
X

,studytime,failures,schoolsup,famsup,activities,higher,internet,famrel,health,absences
0,2,0,yes,no,no,yes,no,4,3,4
1,2,0,no,yes,no,yes,yes,5,3,2
2,2,0,yes,no,no,yes,yes,4,3,6
3,3,0,no,yes,yes,yes,yes,3,5,0
4,2,0,no,yes,no,yes,no,4,5,0
...,...,...,...,...,...,...,...,...,...,...
644,3,1,no,no,yes,yes,yes,5,5,4
645,2,0,no,yes,no,yes,yes,4,1,4
646,2,0,no,no,yes,yes,no,1,5,6
647,1,0,no,no,no,yes,yes,2,2,6
648,1,0,no,no,no,yes,yes,4,5,4

In [24]:
Y=new_df["at_risk"]

In [25]:
Y

0      0
1      0
2      0
3      0
4      0
      ..
644    0
645    0
646    1
647    0
648    0
Name: at_risk, Length: 649, dtype: int64

In [26]:
class_balance= Y.value_counts()

In [27]:
class_balance

at_risk
0    549
1    100
Name: count, dtype: int64

In [28]:
model_data=X.copy()

In [29]:
model_data["at_risk"]=Y

In [30]:
model_data.head()

,studytime,failures,schoolsup,famsup,activities,higher,internet,famrel,health,absences,at_risk
0,2,0,yes,no,no,yes,no,4,3,4,0
1,2,0,no,yes,no,yes,yes,5,3,2,0
2,2,0,yes,no,no,yes,yes,4,3,6,0
3,3,0,no,yes,yes,yes,yes,3,5,0,0
4,2,0,no,yes,no,yes,no,4,5,0,0

In [31]:
model_data.to_csv(
    "student-cleaned-data.csv",
    index=False
)

**day 3 model training and evaluation**

In [33]:

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score,precision_score ,recall_score,f1_score

In [32]:
numeric_features = [
    "studytime",
    "failures",
    "famrel",
    "health",
    "absences"
]

categorical_features = [
    "schoolsup",
    "famsup",
    "activities",
    "higher",
    "internet"
]

In [39]:
#seperate feature (x) and target (y)
x=model_data.drop("at_risk",axis=1)
y=model_data["at_risk"]

In [40]:
from sklearn import preprocessing
#preprocessing
preprocessr=ColumnTransformer(
    transformers=[
        ('cat',OneHotEncoder(),categorical_features),
        ('num',StandardScaler(),numeric_features)
                  ]
)

In [41]:
from sklearn import pipeline
from sklearn.tree import DecisionTreeClassifier
#build pipeline
Pipeline=  pipeline.Pipeline(steps=[
    ('preprocessing',preprocessr),
    ('class', DecisionTreeClassifier())
])

In [42]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [44]:
Pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('cat', OneHotEncoder(),
                                                  ['schoolsup', 'famsup',
                                                   'activities', 'higher',
                                                   'internet']),
                                                 ('num', StandardScaler(),
                                                  ['studytime', 'failures',
                                                   'famrel', 'health',
                                                   'absences'])])),
                ('class', DecisionTreeClassifier())])

In [45]:
y_pred = Pipeline.predict(X_test)

In [46]:
y_pred

array([0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

model **evaluation **bold text**

In [52]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy Score: {accuracy}")

precision = precision_score(y_test, y_pred)
print(f"Precision Score: {precision}")

from sklearn.metrics import recall_score
recall = recall_score(y_test, y_pred)
print(f"Recall Score: {recall}")
f1 = f1_score(y_test, y_pred)
print(f"F1 Score: {f1}")

Accuracy Score: 0.8384615384615385
Precision Score: 0.36363636363636365
Recall Score: 0.5333333333333333
F1 Score: 0.43243243243243246

## Logistic Regression Model

In [56]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

# Build Logistic Regression pipeline
logistic_pipeline = Pipeline(steps=[
    ('preprocessing', preprocessr),
    ('classifier', LogisticRegression(random_state=42))
])

In [57]:
# Fit the Logistic Regression pipeline
logistic_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('cat', OneHotEncoder(),
                                                  ['schoolsup', 'famsup',
                                                   'activities', 'higher',
                                                   'internet']),
                                                 ('num', StandardScaler(),
                                                  ['studytime', 'failures',
                                                   'famrel', 'health',
                                                   'absences'])])),
                ('classifier', LogisticRegression(random_state=42))])

In [58]:
# Make predictions with Logistic Regression
y_pred_lr = logistic_pipeline.predict(X_test)

In [59]:
# Evaluate Logistic Regression Model
accuracy_lr = accuracy_score(y_test, y_pred_lr)
precision_lr = precision_score(y_test, y_pred_lr)
recall_lr = recall_score(y_test, y_pred_lr)
f1_lr = f1_score(y_test, y_pred_lr)

print(f"Logistic Regression Accuracy Score: {accuracy_lr}")
print(f"Logistic Regression Precision Score: {precision_lr}")
print(f"Logistic Regression Recall Score: {recall_lr}")
print(f"Logistic Regression F1 Score: {f1_lr}")

Logistic Regression Accuracy Score: 0.8923076923076924
Logistic Regression Precision Score: 0.5555555555555556
Logistic Regression Recall Score: 0.3333333333333333
Logistic Regression F1 Score: 0.4166666666666667

**compare both logistic and decision tree**

In [62]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import pandas as pd

# ==============================
# Logistic Regression Metrics
# ==============================

accuracy_lr = accuracy_score(y_test, y_pred_lr)
precision_lr = precision_score(y_test, y_pred_lr)
recall_lr = recall_score(y_test, y_pred_lr)
f1_lr = f1_score(y_test, y_pred_lr)


# ==============================
# Decision Tree Metrics
# ==============================

accuracy_dt = accuracy_score(y_test, y_pred)
precision_dt = precision_score(y_test, y_pred)
recall_dt = recall_score(y_test, y_pred)
f1_dt = f1_score(y_test, y_pred)


# ==============================
# Comparison Table
# ==============================

comparison = pd.DataFrame({
    'Metric': ['Accuracy', 'Precision', 'Recall', 'F1 Score'],
    'Logistic Regression': [
        accuracy_lr,
        precision_lr,
        recall_lr,
        f1_lr
    ],
    'Decision Tree': [
        accuracy_dt,
        precision_dt,
        recall_dt,
        f1_dt
    ]
})

print(comparison)

      Metric  Logistic Regression  Decision Tree
0   Accuracy             0.892308       0.838462
1  Precision             0.555556       0.363636
2     Recall             0.333333       0.533333
3   F1 Score             0.416667       0.432432

In [64]:
model_data.shape

(649, 11)